### ISSUE TITLE
Comparison with OOTB composite multifield

### ISSUE THREAD

**Issue by kwin** [merkle-open/aem-generic-multifield#32]
As AEM has composite multifield support since AEM 6.3 I am wondering when this approach should be used over plain https://helpx.adobe.com/experience-manager/6-3/sites/developing/using/reference-materials/granite-ui/api/jcr_root/libs/granite/ui/components/coral/foundation/form/multifield/index.html?

Do you have a comparison somewhere with some guidelines when to use which?

**Comment by mkiti** [comment]
Hello Konrad,
there is currently no overview available that compares the ootb multifield
with the generic multifield.
The generic multifield allows to include a complete dialog within a dialog.
That means your included dialog can consist of multiple tabs (including
richtext and asset upload fields).
I think with the ootb multifield you quickly reach the limits because it
displays everything on one tab.

I guess if you have few coral fields with only a few data items then the
ootb multifield is preferable.
If you expect a lot of corla fields and a higher number of data items then
the Generic Multifield is more clear for the content editor.

Am Fr., 3. Apr. 2020 um 17:56 Uhr schrieb Konrad Windszus <
notifications@github.com>:

**Comment by kwin** [comment]
Thanks for that answer, would be helpful to mention that in the readme.

**Comment by mkiti** [comment]
The Generic Multifield has been around since AEM 6.0 (and earlier in CQ5 classic ui) and thus before the ootb Multifield existed in this form. This is certainly one reason why the persistance format is different. Introducing a flag is one way to control this. Thanks for your feedback

**Comment by mkiti** [comment]
I have just tried out to use a data structure generated by generic multifield with the ootb mulifield. I used a simple link list with title, link and caption field. At least for this case it was no problem to use both solutions.
